const wildersArray = [
    {
        photo : "images/Anthony_card.png",
        nom : "GORSKI",
        prenom : "Anthony",
        age : "31 ans",
        objpro : "Être comme Benoît ❤️",
        hobbies : "Échecs, Manga",
        citation : "",
        linkedin : "https://www.linkedin.com/in/anthony-gorski/",
        github : "https://github.com/GorskiAnthony",
    }
,
    {
        photo : "images/Clement_card.png",
        nom : "FEMENIAS",
        prenom : "Clément",
        age : "32 ans",
        objpro : "Développeur à distance",
        hobbies : "Ski, voyage, tattoo, teach",
        citation : "faut voir grand dans la vie, quitte à voyager à travers le temps au volant d'une voiture, autant en choisir une qui ait de la gueule",
        linkedin : "https://www.linkedin.com/in/clement-femenias-5b7471279/",
        github : "https://github.com/PinpinLaToupie",
    }
,
    {
        photo : "images/Diogo_card.png",
        nom : "CABRAL",
        prenom : "Diogo",
        age : "35 ans",
        objpro : "Actuellement en reconversion professionnelle pour devenir développeur web.",
        hobbies : "Course à pieds, jeux video",
        citation : "Un problème sans solution est un problème mal posé.",
        linkedin : "",
        github : "https://github.com/diogo596",
    }
,
    {
        photo : "images/Doriane_card.png",
        nom : "MULLER LEVEQUE" ,
        prenom : "Doriane",
        age : "30 ans",
        objpro : "Me reconvertir dans un domaine que j'affectionne depuis plusieurs années avec pour ambition de migrer dans une équipe de devs au sein de ma boîte ! :)",
        hobbies : "Principalement les jeux vidéos, je pourrais y passer plusieurs heures tous les jours .. En dehors de cela, je fais du théâtre amateur et je voue un culte à nos comédiens de doublage français ! :D",
        citation : "J'en ai énormément mais j'utilise beaucoup celle-ci : Il y a baleine sous gravillon !!",
        linkedin : "https://www.linkedin.com/in/doriane-muller-leveque-898237a9",
        github : "https://github.com/Doriane23",
    }
,
    {
        photo : "images/Elie_card.png",
        nom : "RAKOTO" ,
        prenom : "Elie",
        age : "30 ans",
        objpro : "",
        hobbies : "",
        citation : "Don't break anyones's heart, they have only one.Break their bones, they have 206",
        linkedin : "",
        github : "",
    }
,
    {
        photo : "images/Flavien_card.png",
        nom : "GAUJARD" ,
        prenom : "Flavien",
        age : "23 ans",
        objpro : "UI/UX Designer",
        hobbies : "Techno, Music, Production, M.A.O, Photography, Design",
        citation : "There is Hell believe me I've seen it. There is a Heaven, let's keeps it a secret",
        linkedin : "https://www.linkedin.com/in/flavien-gaujard/",
        github : "https://github.com/fgaujard",
    }
,
    {
        photo : "images/Francois_card.png",
        nom : "CREUTZER" ,
        prenom : "François",
        age : "39 ans",
        objpro : "Devenir pro du JVS",
        hobbies : "Musique, Rugby",
        citation : "J'adore parler de rien. C'est le seul domaine où j'ai de vagues connaissances.",
        linkedin : "",
        github : "https://github.com/francoiscrtz",
    }
,
    {
        photo : "images/Baris_card.png",
        nom : "GUNAY" ,
        prenom : "Baris",
        age : "27 ans",
        objpro : "Freelance dans le développement Web 🙏",
        hobbies : "Esport / Sport / Musique / Dessin",
        citation : "Le but de l'éducation est de remplir les esprits de façon à les ouvrir.",
        linkedin : "https://www.linkedin.com/in/gunay-baris/",
        github : "https://github.com/BarisRz",
        instagram : "https://www.instagram.com/barisouicestbienmoi/",
        twitter : "",
        facebook : "",
    }
,
    {
        photo : "images/Baptiste_card.png",
        nom : "SAVE" ,
        prenom : "Baptiste",
        age : "24 ans",
        objpro : "Devenir développeur Front-End avec possibilité de formation UI/UX Designer",
        hobbies : "UI/UX Design / Créateur de contenu",
        citation : "Je sais que je ne sais rien - Socrate",
        linkedin : "https://linkedin.com/in/baptiste-save/",
        github : "https://github.com/Batsave",
        instagram : "https://instagram.com/batsave__",
        twitter : "https://twitter.com/batsave",
        facebook : "https://facebook.com/Baptiste.Save.79",
    }
,
    {
        photo : "images/Mehdi_card.png",
        nom : "MEHEMEL" ,
        prenom : "Mehdi",
        age : "37 ans",
        objpro : "Mon projet est de me spécialiser dans la cybersécurité par la suite en poursuivant avec une formation d'Administrateur d'infrastructures sécurisées en alternance avec la Wild Code School",
        hobbies : "Lecture; sport (crossfit); voyages",
        citation : "Ce que l'on fait dans sa vie, résonne dans l'éternité (Maximus dans Gladiator)",
        linkedin : "https://www.linkedin.com/in/mehdi-mehemel-bb5238a4/",
        github : "A DEMANDER IL A MIT DEUX FOIS INSTAGRAM",
        instagram : "https://www.instagram.com/mehdi_meh86/",
        twitter : "https://twitter.com/Mehdiarmando",
        facebook : "https://www.facebook.com/mehdiarmando",
    }
,
    {
        photo : "images/Morgane_card.png",
        nom : "DEBARGE" ,
        prenom : "Morgane",
        age : "29 ans",
        objpro : "Avoir la certification et obtenir un emploi dans le milieu du dev",
        hobbies : "Lecture, séries",
        citation : "Ca ne compte quand même que pour un!",
        linkedin : "",
        github : "",
    }
,
    {
        photo : "images/Oceane_card.png",
        nom : "LAHOUAL",
        prenom : "Océane",
        age : "27 ans",
        objpro : "Devenir Déesse de la magie ",
        hobbies : "Jeux-vidéos, musique, sport, dessin, animes/mangas",
        citation : "Don't break anyones's heart, they have only one.Break their bones, they have 206",
        linkedin : "https://www.linkedin.com/in/oc%C3%A9ane-l-b6312618a/",
        github : "https://github.com/Midunighto",
    }
,
    {
        photo : "images/Tristan_card.png",
        nom : "ZVUNKA" ,
        prenom : "Tristan",
        age : "30 ans",
        objpro : "Devenir Dev Web digne de ce nom!",
        hobbies : "Musique (MAO, DJing), sport, des bon vins",
        citation : "",
        linkedin : "",
        github : "",
    }
,
    {
        photo : "images/Samuel_card.png",
        nom : "FABER" ,
        prenom : "Samuel",
        age : "38 ans",
        objpro : "Devenir le Roi des pirates en trouvant le One Piece ! 🏴‍☠️",
        hobbies : "Pêche 🎣",
        citation : "C'est tout ce que ça te fait quand je te dis qu'on va manger des chips ?",
        linkedin : "A chercher",
        github : "A chercher",
        instagram : "",
        twitter : "",
        facebook : "",
    }
,
    {
        photo : "images/Sebastien_card.png",
        nom : "LACOUR",
        prenom : "Sébastien",
        age : "37 ans",
        objpro : "Gonfleur de roue de train",
        hobbies : "Torturer mes enfants",
        citation : "c'est pas faux",
        linkedin : "",
        github : "https://github.com/sebztz",
        instagram : "",
        twitter : "",
        facebook : "",
    }
,
    {
        photo : "images/Pierre_card.png",
        nom : "COLPART" ,
        prenom : "Pierre",
        age : "32 ans",
        objpro : "Développeur",
        hobbies : "jeux/sport",
        citation : "",
        linkedin : "",
        github : "",
    }
,
    {
        photo : "images/Raphael_card.png",
        nom : "FOULON-BINET" ,
        prenom : "Raphaël",
        age : "18 ans",
        objpro : "Devenir développeur backend principalement Fullstack",
        hobbies : "Animés, Manga, jeux-video, développement",
        citation : "",
        linkedin : "https://www.linkedin.com/in/raphael-foulon-binet-575aa8290/",
        github : "https://github.com/Rapha2202",
    }
,
    {
        photo : "images/Christophe_card.png",
        nom : "BRUNO" ,
        prenom : "Christophe",
        age : "43 ans",
        objpro : "Reconversion en tant que développeur web",
        hobbies : "Sport(basket US, course à pieds), musique, cinema, Tolkien",
        citation : "Qui ne sait être fou n'est pas sage",
        linkedin : "",
        github : "https://github.com/Chrisbrn2625",
    }
,
    {
        photo : "images/Hugo_card.png",
        nom : "DURANT" ,
        prenom : "Hugo",
        age : "23 ans",
        objpro : "Trouver un emploi dans le développement",
        hobbies : "Le gaming, les champions de jeux de combat et les animés/mangas",
        citation : "",
        linkedin : "",
        github : "https://github.com/Palutenya",
    }
,
    {
        photo : "images/Jonathan_card.png",
        nom : "BERNARD" ,
        prenom : "Jonathan",
        age : "34 ans",
        objpro : "Dev' des trucs",
        hobbies : "Jeux video et bière",
        citation : "L'éternité c'est long surtout vers la fin",
        linkedin : "https://www.linkedin.com/in/jonathan-bernard-250733290/",
        github : "https://github.com/Jonathan-Bernard",
    }   
,
    {
        photo : "images/Ghislain_card.png",
        nom : "PELLICANO" ,
        prenom : "Ghislain",
        age : "27 ans",
        objpro : "Mon objectif est d'intégrer une entreprise en tant que développeur web junior ou en tant qu'alternant à la fin de la formation. L'idéal serait de trouver autour de moi dans les landes ou le pays basque ! ",
        hobbies : "Le surf, le ski/snowboard, les jeux vidéos, les films/séries, la musique",
        citation : "Les doutes tuent plus de rêves que les échecs.",
        linkedin : "https://www.linkedin.com/in/ghislain-pellicano-6735aa99/",
        github : "https://github.com/ghispell",
}
,
    {
        photo : "images/Jordan_card.png",
        nom : "MIEGER" ,
        prenom : "Jordan",
        age : "23 ans",
        objpro : "Développeur full-stack en entreprise puis free-lance",
        hobbies : "Sport, foot",
        citation : "C'est quand un moustique se pose sur vos testicules qu'on s'aperçoit qu'on ne peut pas tout régler avec la violence...",
        linkedin : "https://www.linkedin.com/in/jordan-mieger-44373a270",
        github : "http://github.com/JordanMieger",
    }
,
    {
        photo : "images/Jérémy_card.png",
        nom : "ILLIEN" ,
        prenom : "Jérémy",
        age : "26 ans",
        objpro : "Freelance après une période d'entreprise",
        hobbies : "la musique (basse électrique)",
        citation : "à chaque problème sa solution!",
        linkedin : "www.linkedin.com/in/jérémy-illien-380227291",
        github : "https://github.com/Merafath",
}
,
];



export default wildersArray;